"""
Django settings for fin_count project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загрузка переменных окружения из .env файла
# Для production используйте системные переменные окружения
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    # Если python-dotenv не установлен, переменные окружения должны быть установлены в системе
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Секретный ключ загружается из переменной окружения SECRET_KEY
# Если переменная не установлена, генерируется случайный ключ (только для разработки!)
SECRET_KEY = os.getenv('SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
# Режим отладки загружается из переменной окружения DEBUG
# По умолчанию True для разработки, но должен быть False для production
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Разрешенные хосты загружаются из переменной окружения ALLOWED_HOSTS
# Формат: через запятую, без пробелов (например: example.com,www.example.com)
# Для разработки можно использовать: *
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware должен быть как можно выше
    'accounting.middleware.DisableCSRFForAPI',  # Отключаем CSRF для API
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fin_count.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fin_count.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Настройка базы данных из переменных окружения
# Если указан DATABASE_URL, используется он (формат: postgresql://user:password@host:port/dbname)
# Иначе используются отдельные переменные DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
# Если ничего не указано, используется SQLite для разработки

DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    # Использование DATABASE_URL (обычно для production)
    try:
        import dj_database_url
    except ImportError:
        raise ImportError(
            "Для использования DATABASE_URL необходимо установить dj-database-url: "
            "pip install dj-database-url"
        )
    
    try:
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL)
        }
    except Exception as e:
        # Обработка ошибок парсинга DATABASE_URL (неправильный формат и т.д.)
        raise ValueError(
            f"Ошибка при парсинге DATABASE_URL: {e}. "
            f"Проверьте формат DATABASE_URL (например: postgresql://user:password@host:port/dbname)"
        )
elif os.getenv('DB_NAME'):
    # Использование отдельных переменных окружения
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'fin_count'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # SQLite для разработки (по умолчанию)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки системы финансового учета
# Глобальный префикс номеров документов (2 символа)
# Загружается из переменной окружения DOCUMENT_NUMBER_PREFIX
# По умолчанию: 'SC'
DOCUMENT_NUMBER_PREFIX = os.getenv('DOCUMENT_NUMBER_PREFIX', 'SC')

# Django REST Framework настройки
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Требуется авторизация по умолчанию
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# CORS настройки для доступа с любых IP адресов
# ВНИМАНИЕ: Для production рекомендуется ограничить CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = True  # Разрешить все источники (для разработки)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF настройки для API
# Для API endpoints через REST Framework CSRF проверка отключается автоматически
# Но для сессионной аутентификации нужно разрешить определенные источники
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Нужно для чтения через JavaScript
CSRF_USE_SESSIONS = False
