# Generated by Django 5.2.8 on 2025-11-09 07:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный код элемента справочника",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Касса",
                "verbose_name_plural": "Кассы",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код валюты по ISO 4217",
                        max_length=3,
                        unique=True,
                        verbose_name="Код валюты",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, verbose_name="Символ валюты"),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный код элемента справочника",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Должность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["last_name", "first_name", "middle_name"],
            },
        ),
        migrations.CreateModel(
            name="IncomeExpenseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный код элемента справочника",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounting.incomeexpenseitem",
                        verbose_name="Родительская статья",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья доходов/расходов",
                "verbose_name_plural": "Статьи доходов/расходов",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncomeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма оприходования",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={"type": "income"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.incomeexpenseitem",
                        verbose_name="Статья доходов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оприходование денег",
                "verbose_name_plural": "Оприходования денег",
            },
        ),
        migrations.CreateModel(
            name="ExpenseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма расхода"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={"type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.incomeexpenseitem",
                        verbose_name="Статья расходов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход денег",
                "verbose_name_plural": "Расходы денег",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата операции")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма операции"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание операции"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Оприходование денег"),
                            ("expense", "Расход денег"),
                            ("advance_payment", "Выдача подотчетных"),
                            ("advance_report", "Авансовый отчет (строка отчета)"),
                            (
                                "advance_return",
                                "Возврат денег сотрудником (отдельный документ возврата)",
                            ),
                            (
                                "advance_return_report",
                                "Возврат денег по авансовому отчету (в рамках авансового отчета)",
                            ),
                            (
                                "additional_advance_payment",
                                "Дополнительная выдача подотчетных средств",
                            ),
                            ("advance_additional", "Доплата по авансовому отчету"),
                            ("transfer", "Перемещение между кассами"),
                            ("conversion", "Конвертация валют"),
                        ],
                        max_length=30,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "expense_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.expensedocument",
                        verbose_name="Документ расхода",
                    ),
                ),
                (
                    "income_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.incomedocument",
                        verbose_name="Документ оприходования",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.incomeexpenseitem",
                        verbose_name="Статья доходов/расходов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции (Журнал операций)",
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный код элемента справочника",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Курс обмена"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата действия курса")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="accounting.currency",
                        verbose_name="Исходная валюта",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="accounting.currency",
                        verbose_name="Целевая валюта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валют",
                "verbose_name_plural": "Курсы валют",
                "ordering": ["-date", "from_currency", "to_currency"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "date"],
                        name="accounting__from_cu_8d56a4_idx",
                    )
                ],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
        migrations.AddConstraint(
            model_name="incomedocument",
            constraint=models.UniqueConstraint(
                fields=("number", "date"), name="unique_income_document_number_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensedocument",
            constraint=models.UniqueConstraint(
                fields=("number", "date"),
                name="unique_expense_document_number_per_year",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["date", "cash_register", "currency"],
                name="accounting__date_f5b952_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "date"],
                name="accounting__transac_74eec9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["employee", "date"], name="accounting__employe_9c8d36_idx"
            ),
        ),
    ]
