# Generated by Django 5.2.8 on 2025-11-09 08:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalAdvancePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма дополнительной выдачи",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(verbose_name="Цель дополнительной выдачи"),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительная выдача подотчетных средств",
                "verbose_name_plural": "Дополнительные выдачи подотчетных средств",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="additional_advance_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.additionaladvancepayment",
                verbose_name="Дополнительная выдача подотчетных средств",
            ),
        ),
        migrations.CreateModel(
            name="AdvancePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма выдачи"
                    ),
                ),
                ("purpose", models.TextField(verbose_name="Цель выдачи")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Закрыто"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата закрытия"
                    ),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "expense_item",
                    models.ForeignKey(
                        limit_choices_to={"type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.incomeexpenseitem",
                        verbose_name="Статья расходов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача денег подотчетному лицу",
                "verbose_name_plural": "Выдачи денег подотчетным лицам",
            },
        ),
        migrations.AddField(
            model_name="additionaladvancepayment",
            name="original_advance_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="additional_payments",
                to="accounting.advancepayment",
                verbose_name="Первоначальная выдача подотчетных средств",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="advance_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.advancepayment",
                verbose_name="Выдача подотчетных средств",
            ),
        ),
        migrations.CreateModel(
            name="AdvanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Общая сумма расходов",
                    ),
                ),
                (
                    "return_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Сумма возврата",
                    ),
                ),
                (
                    "additional_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Сумма доплаты",
                    ),
                ),
                (
                    "close_advance_payment",
                    models.BooleanField(
                        default=True, verbose_name="Закрыть подотчетные средства"
                    ),
                ),
                (
                    "manual_return_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Возврат денег (ручной)",
                    ),
                ),
                (
                    "manual_additional_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Дополнительная выдача (ручная)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Сдан"),
                            ("confirmed", "Подтвержден"),
                            ("rejected", "Отклонен"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                (
                    "advance_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.advancepayment",
                        verbose_name="Подотчетные средства",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтверждено пользователем",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Авансовый отчет",
                "verbose_name_plural": "Авансовые отчеты",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="advance_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.advancereport",
                verbose_name="Авансовый отчет",
            ),
        ),
        migrations.CreateModel(
            name="AdvanceReportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("date", models.DateTimeField(verbose_name="Дата расхода")),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={"type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.incomeexpenseitem",
                        verbose_name="Статья расходов",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounting.advancereport",
                        verbose_name="Авансовый отчет",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_item",
                        to="accounting.transaction",
                        verbose_name="Операция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка авансового отчета",
                "verbose_name_plural": "Строки авансовых отчетов",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="advance_report_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.advancereportitem",
                verbose_name="Строка авансового отчета",
            ),
        ),
        migrations.CreateModel(
            name="AdvanceReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма возврата"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание возврата"),
                ),
                (
                    "advance_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.advancepayment",
                        verbose_name="Выдача подотчетных средств",
                    ),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возврат денег сотрудником",
                "verbose_name_plural": "Возвраты денег сотрудниками",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="advance_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.advancereturn",
                verbose_name="Возврат денег сотрудником",
            ),
        ),
        migrations.CreateModel(
            name="CashTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "from_cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_from",
                        to="accounting.cashregister",
                        verbose_name="Из кассы",
                    ),
                ),
                (
                    "to_cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_to",
                        to="accounting.cashregister",
                        verbose_name="В кассу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перемещение между кассами",
                "verbose_name_plural": "Перемещения между кассами",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="cash_transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.cashtransfer",
                verbose_name="Перемещение между кассами",
            ),
        ),
        migrations.CreateModel(
            name="CurrencyConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Документ отразился в учете",
                        verbose_name="Проведен",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометка на удаление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "from_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма в исходной валюте",
                    ),
                ),
                (
                    "to_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма в целевой валюте",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Курс обмена"
                    ),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.cashregister",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions_from",
                        to="accounting.currency",
                        verbose_name="Из валюты",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions_to",
                        to="accounting.currency",
                        verbose_name="В валюту",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конвертация валют",
                "verbose_name_plural": "Конвертации валют",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency_conversion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.currencyconversion",
                verbose_name="Конвертация валют",
            ),
        ),
        migrations.AddConstraint(
            model_name="advancepayment",
            constraint=models.UniqueConstraint(
                fields=("number", "date"), name="unique_advance_payment_number_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="additionaladvancepayment",
            constraint=models.UniqueConstraint(
                fields=("number", "date"),
                name="unique_additional_advance_payment_number_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="advancereport",
            constraint=models.UniqueConstraint(
                fields=("number", "date"), name="unique_advance_report_number_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="advancereturn",
            constraint=models.UniqueConstraint(
                fields=("number", "date"), name="unique_advance_return_number_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashtransfer",
            constraint=models.UniqueConstraint(
                fields=("number", "date"), name="unique_cash_transfer_number_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyconversion",
            constraint=models.UniqueConstraint(
                fields=("number", "date"),
                name="unique_currency_conversion_number_per_year",
            ),
        ),
    ]
