# Generated by Django 5.2.8 on 2025-11-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_additionaladvancepayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=15, verbose_name="Курс обмена"
            ),
        ),
    ]
