# Generated by Django 5.2.8 on 2025-11-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_change_currency_rate_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashregister",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                max_length=50,
                null=True,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                max_length=50,
                null=True,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                max_length=50,
                null=True,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="incomeexpenseitem",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Может быть введен вручную (до 50 символов) или сгенерирован автоматически",
                max_length=50,
                null=True,
                verbose_name="Код",
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("code",),
                name="unique_currency_code",
            ),
        ),
    ]
