# Generated by Django 5.2.8 on 2025-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_add_reference_code_generation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cashregister",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("code",),
                name="unique_cashregister_code",
            ),
        ),
    ]
