# Generated by Django 5.2.8 on 2025-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_add_unique_constraints_for_reference_codes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="incomeexpenseitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("code",),
                name="unique_incomeexpenseitem_code",
            ),
        ),
    ]
