# Generated by Django 5.2.8 on 2025-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_add_employee_and_currencyrate_unique_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="currencyrate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("code",),
                name="unique_currencyrate_code",
            ),
        ),
    ]
