# Generated by Django 5.2.8 on 2025-11-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_add_currencyrate_unique_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionaladvancepayment",
            name="employee",
        ),
    ]
